trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w1122h2e-vs22c-vmware-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w1122h2e-vs22c
      provider: vmware
      configuration: vagrant
      parent: w1122h2e-vs22c

  - template: ../../cd-stages.yml
    parameters:
      image: w1122h2e-vs22c
      provider: vmware
      configuration: vagrant
