trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w1021h2eltsc-hyperv-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w1021h2eltsc
      provider: hyperv
      configuration: vagrant
      parent: w1021h2eltsc

  - template: ../../cd-stages.yml
    parameters:
      image: w1021h2eltsc
      provider: hyperv
      configuration: vagrant
