trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-server.2022-standard-core.hyperv

stages:
  - template: ../../stages.yml
    parameters:
      sample: sql-server
      image: 2019-developer-windows-server-core
      provider: hyperv
