trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: CI

  jobs:
  - job: build
    displayName: Build
    pool:
      name: Default
      demands:
      - PACKER_CACHE_DIR
    workspace:
      clean: all
    timeoutInMinutes: 120

    steps:
    - checkout: self
      submodules: recursive

    # - powershell: |
    #     .\ci.ps1 build u16s-hyperv-core
    #   displayName: Build u16s-hyperv-core
    # - powershell: |
    #     .\ci.ps1 build u16s-hyperv-sysprep
    #   displayName: Build u16s-hyperv-sysprep
    # - powershell: |
    #     .\ci.ps1 build u16s-dc-hyperv-core
    #   displayName: Build u16s-dc-hyperv-core
    # - powershell: |
    #     .\ci.ps1 build u16s-dc-hyperv-sysprep
    #   displayName: Build u16s-dc-hyperv-sysprep

    - powershell: |
        .\ci.ps1 build ws2019sc-hyperv-core
      displayName: Build ws2019sc-hyperv-core
    - powershell: |
        .\ci.ps1 build ws2019sc-hyperv-sysprep
      displayName: Build ws2019sc-hyperv-sysprep
    - powershell: |
        .\ci.ps1 build ws2019sc-hyperv-core
      displayName: Build ws2019sc-de-hyperv-core
    - powershell: |
        .\ci.ps1 build ws2019sc-hyperv-sysprep
      displayName: Build ws2019sc-de-hyperv-sysprep
