trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: CI

  jobs:
  - job: build
    displayName: Build
    pool:
      name: Default

    steps:
    - powershell: |
        .\ci.ps1 info
      displayName: Diagnostics
    - powershell: |
        .\ci.ps1 restore u16s-hyperv-core
      displayName: Restore
