trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: CI

  jobs:
  - job: build
    displayName: Build
    pool:
      name: Default
      demands:
      - PACKER_CACHE_DIR
    workspace:
      clean: all

    steps:
    - powershell: |
        .\ci.ps1 info
      displayName: Info
    - powershell: |
        .\ci.ps1 build u16s-hyperv-core
      displayName: Build 1 Core
    - powershell: |
        .\ci.ps1 rebuild u16s-hyperv-sysprep
      displayName: Build 1 Sysprep
    - powershell: |
        .\ci.ps1 build u16s-dc-hyperv-core
      displayName: Build 2 Core
    - powershell: |
        .\ci.ps1 rebuild u16s-dc-hyperv-sysprep
      displayName: Build 2 Sysprep
