trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: CI

  jobs:
  - template: azure-pipelines.ci.build.yml
    parameters:
      jobs:
      - job: u16s
        displayName: u16s
      - job: u16s_dc
        displayName: u16s-dc
        dependsOn:
        - u16s
