parameters:
  jobs: []

jobs:
- ${{ each job in parameters.jobs }}:
  - ${{ each pair in job }}:
      ${{ if ne(pair.key, 'dependsOn') }}:
        ${{ pair.key }}: ${{ pair.value }}
    pool:
      name: Default
      demands:
      - PACKER_CACHE_DIR
    timeoutInMinutes: 120

    steps:
    - checkout: self
      submodules: recursive

    - powershell: |
        .\ci.ps1 info

#   - powershell: |
#       .\ci.ps1 rebuild ${{ parameters.name }}-${{ parameters.provider }}-${{ parameters.variant }}
#     displayName: Build ${{ parameters.name }}-${{ parameters.provider }}-${{ parameters.variant }}
