trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: CI

  jobs:
  - template: azure-pipelines.ci.build.yml
    parameters:
      name: u16s
      provider: hyperv
      variant: core

  - template: azure-pipelines.ci.build.yml
    parameters:
      name: u16s
      provider: hyperv
      variant: sysprep

  - template: azure-pipelines.ci.build.yml
    parameters:
      name: ws2019sc
      provider: hyperv
      variant: core

  - template: azure-pipelines.ci.build.yml
    parameters:
      name: ws2019sc
      provider: hyperv
      variant: sysprep
