parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: build_${{ image.name }}_${{ provider }}_core
      displayName: Build ${{ image.displayName }}-${{ provider }}-core
      pool:
        name: Default
        demands:
        - PACKER_CACHE_DIR
        - PACKER_${{ provider }}
      timeoutInMinutes: 120
      dependsOn:
      - ${{ if image.parent }}:
        - build_${{ image.parent }}_${{ provider }}_core

      steps:
      - checkout: self
        submodules: recursive

      - powershell: |
          .\ci.ps1 restore ${{ image.displayName }}-${{ provider }}-core
        displayName: Build ${{ image.displayName }}-${{ provider }}-core

    - job: build_${{ image.name }}_${{ provider }}_sysprep
      displayName: Build ${{ image.displayName }}-${{ provider }}-sysprep
      pool:
        name: Default
        demands:
        - PACKER_CACHE_DIR
        - PACKER_${{ provider }}
      timeoutInMinutes: 120
      dependsOn:
      - build_${{ image.name }}_${{ provider }}_core

      steps:
      - checkout: self
        submodules: recursive

      - powershell: |
          .\ci.ps1 restore ${{ image.displayName }}-${{ provider }}-sysprep
        displayName: Build ${{ image.displayName }}-${{ provider }}-sysprep
