trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: CI

  jobs:
  - template: azure-pipelines.ci.build.yml
    parameters:
      name: u16s_hyperv_core
      configuration: u16s_hyperv_core

  - template: azure-pipelines.ci.build.yml
    parameters:
      name: u16s_hyperv_sysprep
      configuration: u16s_hyperv_sysprep
    dependsOn: build_u16s_hyperv_core
