parameters:
  configurations: []
  platforms: []

jobs:
- ${{ each configuration in parameters.configurations }}:
  - ${{ each platform in parameters.platforms }}:
  - job: build_${{ configuration.name }}_${{ platform.name }}
    displayName: Build ${{ configuration.displayName }} ${{ platform.name }}
    pool:
      name: Default
      demands:
      - PACKER_CACHE_DIR
    timeoutInMinutes: 120

    steps:
    - checkout: self
      submodules: recursive

    - powershell: |
        .\ci.ps1 info ${{ configuration.name }}-${{ platform.name }}

#   - powershell: |
#       .\ci.ps1 rebuild ${{ parameters.name }}-${{ parameters.provider }}-${{ parameters.variant }}
#     displayName: Build ${{ parameters.name }}-${{ parameters.provider }}-${{ parameters.variant }}
