parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: build_${{ image.name }}_${{ provider }}_core
      displayName: Build ${{ image.displayName }}-${{ provider }}-core
      pool:
        name: Default
        demands:
        - PACKER_CACHE_DIR
        - PACKER_${{ provider }}
      workspace:
        clean: all
      timeoutInMinutes: 120
      dependsOn:
      - ${{ if image.parent }}:
        - build_${{ image.parent }}_${{ provider }}_core

      steps:
      - checkout: self
        submodules: recursive

      - powershell: |
          .\ci.ps1 build ${{ image.displayName }}-${{ provider }}-core
        displayName: Build

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: build
          archiveType: tar
          tarCompression: gz
          archiveFile: $(Build.ArtifactStagingDirectory)/build.$(Build.BuildId).tar.gz

      - task: PublishBuildArtifacts@1
        displayName: Publish - Artifacts
        inputs:
          artifactName: ci-build-${{ image.displayName }}-${{ provider }}-core
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          publishLocation: filePath
          targetPath: $(artifacts-targetpath)

    - job: build_${{ image.name }}_${{ provider }}_sysprep
      displayName: Build ${{ image.displayName }}-${{ provider }}-sysprep
      pool:
        name: Default
        demands:
        - PACKER_CACHE_DIR
        - PACKER_${{ provider }}
      workspace:
        clean: all
      timeoutInMinutes: 120
      dependsOn:
      - build_${{ image.name }}_${{ provider }}_core

      steps:
      - checkout: self
        submodules: recursive

      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: ci-build-${{ image.displayName }}-${{ provider }}-core

      - powershell: |
          .\ci.ps1 build ${{ image.displayName }}-${{ provider }}-sysprep
        displayName: Build

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: build
          archiveType: tar
          tarCompression: gz
          archiveFile: $(Build.ArtifactStagingDirectory)/build.$(Build.BuildId).tar.gz

      - task: PublishBuildArtifacts@1
        displayName: Publish - Artifacts
        inputs:
          artifactName: ci-build-${{ image.displayName }}-${{ provider }}-sysprep
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          publishLocation: filePath
          targetPath: $(artifacts-targetpath)
