parameters:
  name: ''
  provider: ''
  variant: ''

jobs:
- job: build_${{ parameters.name }}_${{ parameters.provider }}_${{ parameters.variant }}
  displayName: Build ${{ parameters.name }}-${{ parameters.provider }}-${{ parameters.variant }}
  pool:
    name: Default
    demands:
    - PACKER_CACHE_DIR
  workspace:
    clean: all
  timeoutInMinutes: 120

  steps:
  - checkout: self
    submodules: recursive

  - powershell: |
      .\ci.ps1 build ${{ parameters.name }}-${{ parameters.provider }}-${{ parameters.variant }}
    displayName: Build ${{ parameters.name }}-${{ parameters.provider }}-${{ parameters.variant }}
