trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: CI

  jobs:
  - job: build
    displayName: Build
    pool:
      name: Default
      demands:
      - PACKER_CACHE_DIR

    steps:
    - powershell: |
        .\ci.ps1 info
      displayName: Info
    - powershell: |
        .\ci.ps1 restore u16s-hyperv-core
      displayName: Restore
    - powershell: |
        .\ci.ps1 build u16s-hyperv-core
      displayName: Build
