parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: build_${{ image.name }}_${{ provider.name }}
      displayName: Build ${{ image.displayName }}-${{ provider.name }}
      pool:
        name: Default
        demands:
        - PACKER_CACHE_DIR
      timeoutInMinutes: 120

      steps:
      - checkout: self
        submodules: recursive

      - powershell: |
          .\ci.ps1 restore ${{ image.displayName }}-${{ provider.name }}
        displayName: Build ${{ image.displayName }}-${{ provider.name }}

#   - powershell: |
#       .\ci.ps1 rebuild ${{ parameters.name }}-${{ parameters.provider }}-${{ parameters.variant }}
#     displayName: Build ${{ parameters.name }}-${{ parameters.provider }}-${{ parameters.variant }}
