trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2022s-dd-vs19c-hyperv-core
      trigger:
        branches:
          include:
            - master

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2022s-dd-vs19c
      provider: hyperv
      configuration: vagrant
      parent: ws2022s-dd-vs19c

  - template: ../../cd-stages.yml
    parameters:
      image: ws2022s-dd-vs19c
      provider: hyperv
      configuration: vagrant
