trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2022s-dd-virtualbox-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2022s-dd-vs19c
      provider: virtualbox
      configuration: core
      parent: ws2022s-dd
