trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w1022h2e-vs22c-hyperv-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w1022h2e-vs22c
      provider: hyperv
      configuration: vagrant
      parent: w1022h2e-vs22c

  - template: ../../cd-stages.yml
    parameters:
      image: w1022h2e-vs22c
      provider: hyperv
      configuration: vagrant
