trigger: none
pr: none

stages:
- stage: build
  displayName: Build

  jobs:
  - template: ../build.yml
    parameters:
      images:
      - name: u16s
      providers:
      - virtualbox

- stage: deploy
  displayName: Deploy

  jobs:
  - template: ../deploy.yml
    parameters:
      images:
      - name: u16s
      providers:
      - virtualbox
