trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2019sc-hyperv-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2019sc-iis
      provider: hyperv
      configuration: core
      parent: ws2019sc
