---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w12r2s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w12r2s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_packer_w12r2s::default]
    verifier:
      inspec_tests:
        - test/smoke/default
