trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: u2004d-hyperv-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: u2004d-dc
      provider: hyperv
      configuration: core
      parent: u2004d
