trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: u2004d-virtualbox-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: u2004d-dc
      provider: virtualbox
      configuration: core
      parent: u2004d
