trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w102004e-dc-hyperv-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w102004e-dc-vs19p
      provider: hyperv
      configuration: core
      parent: w102004e-dc
