trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w102009e-virtualbox-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w102009e-dc
      provider: virtualbox
      configuration: core
      parent: w102009e
