trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: u2004s-dc-virtualbox-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: u2004s-dc
      provider: virtualbox
      configuration: vagrant
      parent: u2004s-dc

  - template: ../../cd-stages.yml
    parameters:
      image: u2004s-dc
      provider: virtualbox
      configuration: vagrant
