trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w1022h2e-vmware-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w1022h2e
      provider: vmware
      configuration: vagrant
      parent: w1022h2e

  - template: ../../cd-stages.yml
    parameters:
      image: w1022h2e
      provider: vmware
      configuration: vagrant
