trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: wsips-hyperv-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: wsips
      provider: hyperv
      configuration: vagrant
      parent: wsips

  - template: ../../cd-stages.yml
    parameters:
      image: wsips
      provider: hyperv
      configuration: vagrant
