trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w1122h2e-virtualbox-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w1122h2e-dd
      provider: virtualbox
      configuration: core
      parent: w1122h2e
