trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-server.2022-standard.hyperv

stages:
  - template: ../../stages.yml
    parameters:
      sample: iis
      image: windows-server
      provider: hyperv
