trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2022sc-sql19d-virtualbox-core
      trigger:
        branches:
          include:
            - master

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2022sc-sql19d
      provider: virtualbox
      configuration: vagrant
      parent: ws2022sc-sql19d

  - template: ../../cd-stages.yml
    parameters:
      image: ws2022sc-sql19d
      provider: virtualbox
      configuration: vagrant
