trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2019s-hyperv-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2019s
      provider: hyperv
      configuration: vagrant
      parent: ws2019s

  - template: ../../cd-stages.yml
    parameters:
      image: ws2019s
      provider: hyperv
      configuration: vagrant
