trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2022s-de-hyperv-core
      trigger:
        branches:
          include:
            - master

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2022s-de
      provider: hyperv
      configuration: vagrant
      parent: ws2022s-de

  - template: ../../cd-stages.yml
    parameters:
      image: ws2022s-de
      provider: hyperv
      configuration: vagrant
