trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: u1604s-virtualbox-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: u1604d
      provider: virtualbox
      configuration: core
      parent: u1604s
