trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: u1604d-virtualbox-core
      trigger:
        branches:
          include:
            - '*'

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: u1604d
      provider: virtualbox
      configuration: vagrant
      parent: u1604d

  - template: ../../cd-stages.yml
    parameters:
      image: u1604d
      provider: virtualbox
      configuration: vagrant
