trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: dc-w10-hyperv-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w102101e-dc-vs19c
      provider: hyperv
      configuration: core
      parent: w102101e-dc
