trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w1022h2e-hyperv-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w1022h2e-dd
      provider: hyperv
      configuration: core
      parent: w1022h2e
