trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2022s-virtualbox-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2022s
      provider: virtualbox
      configuration: vagrant
      parent: ws2022s

  - template: ../../cd-stages.yml
    parameters:
      image: ws2022s
      provider: virtualbox
      configuration: vagrant
