trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2019sc-virtualbox-core
      trigger:
        branches:
          include:
            - master

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2019sc-de
      provider: virtualbox
      configuration: core
      parent: ws2019sc
