trigger: none
pr: none

stages:
- stage: ci
  displayName: CI
  variables:
  - group: artifacts-localnetwork

  jobs:
  - template: azure-pipelines.ci.build.yml
    parameters:
      images:
      - name: ws2019sc
        displayName: ws2019sc
      providers:
      - virtualbox
      - hyperv
