parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: ${{ join('_', image.name) }}_${{ provider }}_vagrant_build
      displayName: Build ${{ join('-', image.name) }}-${{ provider }}-vagrant
      pool:
        name: Default
        demands:
        - PACKER_${{ provider }}
      workspace:
        clean: all
      timeoutInMinutes: 120

      steps:
      - checkout: self
        submodules: recursive

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: specific
          project: packer
          pipeline: ${{ join('-', image.name) }}-core
          downloadType: single
          artifactName: ${{ join('-', image.name) }}-${{ provider }}-core-build

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: $(Build.ArtifactStagingDirectory)/**/build.*
          destinationFolder: build/${{ join('-', image.name) }}

      - task: DeleteFiles@1
        inputs:
          sourceFolder: $(Build.ArtifactStagingDirectory)
          contents: '**'
        condition: always()

      - powershell: |
          .\ci.ps1 build ${{ join('-', image.name) }}-${{ provider }}-sysprep
        displayName: Build

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: build/${{ join('-', image.name) }}/${{ provider }}-sysprep
          archiveType: tar
          tarCompression: none
          archiveFile: $(Build.ArtifactStagingDirectory)/build.tar

      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: ${{ join('-', image.name) }}-${{ provider }}-vagrant-build
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          publishLocation: filePath
          targetPath: $(artifacts-targetpath)\$(Build.BuildId)

      - powershell: |
          .\ci.ps1 clean
        displayName: Clean
        condition: always()

      - task: DeleteFiles@1
        inputs:
          sourceFolder: $(Build.ArtifactStagingDirectory)
          contents: '**'
        condition: always()
