trigger: none
pr: none

stages:
- stage: ci
  displayName: CI
  variables:
  - group: artifacts-localnetwork

  jobs:
  - template: azure-pipelines.ci.build.yml
    parameters:
      images:
      - name: ws2019s_iis
        displayName: ws2019s-iis
        parentName: ws2019s
        parentDisplayName: ws2019s
      - name: ws2019sc_iis
        displayName: ws2019sc-iis
        parentName: ws2019sc
        parentDisplayName: ws2019sc
      providers:
      - virtualbox
      - hyperv
