trigger: none
pr: none

stages:
- stage: ci
  displayName: CI
  variables:
  - group: artifacts-localnetwork

  jobs:
  - template: azure-pipelines.ci.build.yml
    parameters:
      images:
      - name: ws2019s_sql17d
        displayName: ws2019s-sql17d
        parentName: ws2019s
        parentDisplayName: ws2019s
      providers:
      - virtualbox
      - hyperv
