parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: ${{ join('_', image.name) }}_${{ provider }}_vagrant_deploy
      displayName: Deploy ${{ join('-', image.name) }}-${{ provider }}-vagrant
      pool:
        name: Default
        demands:
        - PACKER_${{ provider }}
      variables:
      - group: artifacts
      workspace:
        clean: all
      timeoutInMinutes: 120

      steps:
      - checkout: self
        submodules: recursive

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: specific
          project: packer
          pipeline: ${{ join('-', image.name) }}-vagrant
          downloadType: single
          artifactName: ${{ join('-', image.name) }}-${{ provider }}-vagrant-build

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: $(Build.ArtifactStagingDirectory)/**/build.*
          destinationFolder: build/${{ join('-', image.name) }}

      - task: DeleteFiles@1
        inputs:
          sourceFolder: $(Build.ArtifactStagingDirectory)
          contents: '**'
        condition: always()

      - powershell: |
          $env:VAGRANT_DEFAULT_PROVIDER='${{ provider }}'
          vagrant up ${{ join('-', image.name) }}-local
        displayName: Build

      - powershell: |
          vagrant destroy -f ${{ join('-', image.name) }}-local
        displayName: Clean Machine
        condition: always()

      - powershell: |
          vagrant box remove gusztavvargadr/${{ join('-', image.name) }}-local --provider '${{ provider }}'
        displayName: Clean Box
        condition: always()

      - powershell: |
          .\ci.ps1 clean
        displayName: Clean Build
        condition: always()
