parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: ${{ join('_', image.name) }}_${{ provider }}_empty_build
      displayName: Build ${{ join('-', image.name) }}-${{ provider }}-empty
      pool:
        name: Default
        demands:
        - PACKER_${{ provider }}
      variables:
      - group: artifacts
      workspace:
        clean: all
      timeoutInMinutes: 120

      steps:
      - checkout: self
        submodules: recursive

      - powershell: |
          .\ci.ps1 build ${{ join('-', image.name) }}-${{ provider }}-empty
        displayName: Build

      - powershell: |
          $env:VAGRANT_DEFAULT_PROVIDER='${{ provider }}'
          vagrant up ${{ join('-', image.name) }}-local-empty
        displayName: Test

      - powershell: |
          vagrant destroy -f ${{ join('-', image.name) }}-local-empty
        displayName: Clean Test Machine
        condition: always()

      - powershell: |
          vagrant box remove gusztavvargadr/${{ join('-', image.name) }}-local-empty --provider '${{ provider }}'
        displayName: Clean Test Box
        condition: always()

      - powershell: |
          .\ci.ps1 clean
        displayName: Clean Build
        condition: always()
