parameters:
  image: ''
  provider: ''
  configuration: ''

stages:
  - stage: cd
    displayName: CD

    jobs:
      - job: publish
        displayName: Publish ${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}

        pool:
          vmImage: 'ubuntu-20.04'

        variables:
          - group: environment-vagrantcloud

        steps:
          - checkout: self
            submodules: recursive

          - script: |
              mkdir tmp
              cd tmp
              git clone https://gist.github.com/1f0d7dddc7f48549368eaaedf19bfe55.git chef-gist
              cd chef-gist
              POLICY_NAME=vagrant bash build.sh
            displayName: Initialize agent

          - script: |
              dotnet --info

              dotnet tool restore
            displayName: Initialize .NET

          - script: |
              vagrant --version
              vagrant plugin list

              vagrant box list
              vagrant global-status --prune
            displayName: Initialize Vagrant

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: build
              path: $(System.DefaultWorkingDirectory)/build/${{ parameters.image }}/${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Artifacts - Download

          - script: |
              dotnet cake build.cake --target=publish --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Build - Publish
            env:
              VAGRANT_CLOUD_TOKEN: $(environment-vagrant-cloud-token)

          - script: |
              dotnet cake build.cake --target=clean --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }} --recursive true
            displayName: Build - Clean
            condition: always()

      - job: release
        displayName: Release ${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

        pool:
          vmImage: 'ubuntu-20.04'

        dependsOn: publish

        steps:
          - checkout: self
            submodules: recursive

          - script: |
              mkdir tmp
              cd tmp
              git clone https://gist.github.com/1f0d7dddc7f48549368eaaedf19bfe55.git chef-gist
              cd chef-gist
              POLICY_NAME=vagrant bash build.sh
            displayName: Initialize agent

          - script: |
              dotnet --info

              dotnet tool restore
            displayName: Initialize .NET

          - script: |
              vagrant --version
              vagrant plugin list

              vagrant box list
              vagrant global-status --prune
            displayName: Initialize Vagrant

          - script: |
              dotnet cake build.cake --target=download --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Build - Download

          - script: |
              dotnet cake build.cake --target=clean --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }} --recursive true
            displayName: Build - Clean
            condition: always()
