parameters:
  image: ""
  provider: ""
  configuration: ""

stages:
  - stage: cd
    displayName: CD
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    jobs:
      - job: publish
        displayName: Publish ${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
        pool:
          vmImage: ubuntu-20.04
        workspace:
          clean: all
        timeoutInMinutes: 240
        variables:
          - group: environment-vagrantcloud

        steps:
          - checkout: self
            submodules: recursive

          - script: |
              rm -Rf /usr/share/dotnet/sdk/2.1.*
              rm -Rf /usr/share/dotnet/sdk/2.2.*
              rm -Rf /usr/share/dotnet/sdk/3.0.*
              df -H
            displayName: Init - Disk space

          - script: |
              dotnet --info

              dotnet tool restore
            displayName: Initialize .NET

          - script: |
              wget -q https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_x86_64.deb
              sudo dpkg -i vagrant_2.2.10_x86_64.deb
              rm vagrant_2.2.10_x86_64.deb
              vagrant --version
            displayName: Init - Vagrant

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: build
              path: $(System.DefaultWorkingDirectory)/build/${{ parameters.image }}/${{ parameters.provider }}-${{ parameters.configuration }}
              runVersion: latestFromBranch
              runBranch: $(Build.SourceBranch)
            displayName: Artifacts - Download

          - script: |
              ~/.dotnet/tools/dotnet-cake build.cake --target=publish --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Build - Publish
            env:
              VAGRANT_CLOUD_TOKEN: $(environment-vagrant-cloud-token)

          - script: |
              ~/.dotnet/tools/dotnet-cake build.cake --target=clean
            displayName: Build - Clean
            condition: always()

      - job: download
        displayName: Download ${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
        pool:
          name: core-windows
        workspace:
          clean: all
        timeoutInMinutes: 240
        dependsOn: publish

        steps:
          - checkout: self
            submodules: recursive

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: build
              path: $(System.DefaultWorkingDirectory)/build/${{ parameters.image }}/${{ parameters.provider }}-${{ parameters.configuration }}
              runVersion: latestFromBranch
              runBranch: $(Build.SourceBranch)
              patterns: "**/checksum.*"
            displayName: Artifacts - Download

          - script: |
              dotnet cake build.cake --target=download --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Build - Download

          - script: |
              dotnet cake build.cake --target=clean
            displayName: Build - Clean
            condition: always()
