parameters:
  image: ""
  provider: ""
  configuration: ""

stages:
  - stage: cd
    displayName: CD
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    jobs:
      - job: publish
        displayName: Publish ${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}

        pool:
          vmImage: ubuntu-20.04

        workspace:
          clean: all
        variables:
          - group: environment-vagrantcloud

        steps:
          - checkout: self
            submodules: recursive

          - script: |
              dotnet --info

              dotnet tool restore
            displayName: Initialize .NET

          - script: |
              wget -q https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_x86_64.deb
              sudo dpkg -i vagrant_2.2.18_x86_64.deb
              rm vagrant_2.2.18_x86_64.deb

              vagrant --version
              vagrant plugin list

              vagrant box list
              vagrant global-status
            displayName: Initialize Vagrant

          - script: |
              rm -Rf /usr/share/dotnet/sdk/2.1.*
              rm -Rf /usr/share/dotnet/sdk/2.2.*
              rm -Rf /usr/share/dotnet/sdk/3.0.*
              df -H
            displayName: Initialize disk

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: build
              path: $(System.DefaultWorkingDirectory)/build/${{ parameters.image }}/${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Artifacts - Download

          - script: |
              dotnet cake build.cake --target=publish --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Build - Publish
            env:
              VAGRANT_CLOUD_TOKEN: $(environment-vagrant-cloud-token)

          - script: |
              dotnet cake build.cake --target=clean --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Build - Clean
            condition: always()

      - job: download
        displayName: Download ${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}

        pool:
          vmImage: ubuntu-20.04

        workspace:
          clean: all
        dependsOn: publish

        steps:
          - checkout: self
            submodules: recursive

          - script: |
              dotnet --info

              dotnet tool restore
            displayName: Initialize .NET

          - script: |
              wget -q https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_x86_64.deb
              sudo dpkg -i vagrant_2.2.18_x86_64.deb
              rm vagrant_2.2.18_x86_64.deb

              vagrant --version
              vagrant plugin list

              vagrant box list
              vagrant global-status
            displayName: Initialize Vagrant

          - script: |
              rm -Rf /usr/share/dotnet/sdk/2.1.*
              rm -Rf /usr/share/dotnet/sdk/2.2.*
              rm -Rf /usr/share/dotnet/sdk/3.0.*
              df -H
            displayName: Initialize disk

          - script: |
              dotnet cake build.cake --target=download --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Build - Download

          - script: |
              dotnet cake build.cake --target=clean --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Build - Clean
            condition: always()
