parameters:
  image: ''
  provider: ''
  configuration: ''

jobs:
  - job: test
    displayName: Test
    pool:
      name: Default
      demands:
        - AZP_AGENT_PACKER -equals ${{ parameters.provider }}
        - AZP_AGENT_VAGRANT -equals ${{ parameters.provider }}
    workspace:
      clean: all
    timeoutInMinutes: 120

    steps:
      - checkout: self
        submodules: recursive

      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          artifact: build
          path: $(System.DefaultWorkingDirectory)/build/${{ parameters.image }}/${{ parameters.provider }}-${{ parameters.configuration }}
        displayName: Artifacts - Download

      - script: |
          dotnet cake build.cake --target=test --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
        displayName: Build - Test

      - script: |
          dotnet cake build.cake --target=clean --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
        displayName: Build - Clean
        condition: always()
