parameters:
  image: ''
  provider: ''
  configuration: ''
  parent: ''
  parentDefinitionId: ''

stages:
  - stage: build
    displayName: Build

    jobs:
      - template: ./ci-jobs-build.yml
        parameters:
          image: ${{ parameters.image }}
          provider: ${{ parameters.provider }}
          configuration: ${{ parameters.configuration }}
          parent: ${{ parameters.parent }}
          parentDefinitionId: ${{ parameters.parentDefinitionId }}

  - stage: test
    displayName: Test

    jobs:
      - template: ./ci-jobs-test.yml
        parameters:
          image: ${{ parameters.image }}
          provider: ${{ parameters.provider }}
          configuration: ${{ parameters.configuration }}
