parameters:
  image: ""
  provider: ""
  configuration: ""
  parent: ""

stages:
  - stage: ci
    displayName: CI

    jobs:
      - job: build
        displayName: Build ${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}

        pool:
          name: Default
          demands:
            - AZP_AGENT_DOTNET
            - AZP_AGENT_PACKER
            - AZP_AGENT_VAGRANT
            - AZP_AGENT_${{ parameters.provider }}

        workspace:
          clean: all
        timeoutInMinutes: 120

        steps:
          - checkout: self
            submodules: recursive

          - script: |
              dotnet --info

              dotnet tool restore
            displayName: Initialize .NET

          - ${{ if parameters.parent }}:
              - task: DownloadPipelineArtifact@2
                inputs:
                  artifact: build
                  path: $(System.DefaultWorkingDirectory)/build/${{ parameters.parent }}/${{ parameters.provider }}-core
                  source: specific
                  project: $(System.TeamProjectId)
                  pipeline: $(resources.pipeline.parent.pipelineID)
                  runVersion: latestFromBranch
                  runBranch: $(Build.SourceBranch)
                displayName: Artifacts - Download

          - script: |
              dotnet cake build.cake --target=test --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
            displayName: Build - Test

          - publish: $(System.DefaultWorkingDirectory)/build/${{ parameters.image }}/${{ parameters.provider }}-${{ parameters.configuration }}
            artifact: build
            displayName: Artifacts - Publish

          - script: |
              dotnet cake build.cake --target=clean
            displayName: Build - Clean
            condition: always()
