parameters:
  image: ''
  configuration: ''
  provider: ''

jobs:
- job: test
  displayName: Test
  pool:
    name: Default
    demands:
    - AZP_AGENT_PACKER -equals ${{ parameters.provider }}
    - AZP_AGENT_VAGRANT -equals ${{ parameters.provider }}
  workspace:
    clean: all
  timeoutInMinutes: 120

  steps:
  - checkout: self
    submodules: recursive

  - download: current
    artifact: build

  - script: |
      dotnet cake build.cake --target=test --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
    displayName: Test
