parameters:
  image: ''
  configuration: ''
  provider: ''

jobs:
  - job: build
    displayName: Build
    pool:
      name: Default
      demands:
        - AZP_AGENT_PACKER -equals ${{ parameters.provider }}
        - AZP_AGENT_VAGRANT -equals ${{ parameters.provider }}
    workspace:
      clean: all
    timeoutInMinutes: 120

    steps:
      - checkout: self
        submodules: recursive

      - script: |
          dotnet cake build.cake --target=restore --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
        displayName: Restore

      - script: |
          dotnet cake build.cake --target=build --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
        displayName: Build

      - publish: $(System.DefaultWorkingDirectory)/build/${{ parameters.image }}/${{ parameters.provider }}-${{ parameters.configuration }}
        artifact: build
        displayName: Artifacts

      - script: |
          dotnet cake build.cake --target=clean --configuration=${{ parameters.image }}-${{ parameters.provider }}-${{ parameters.configuration }}
        displayName: Clean
        condition: always()
