parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: ${{ join('_', image.name) }}_${{ provider }}_core_build
      displayName: Build ${{ join('-', image.name) }}-${{ provider }}-core
      pool:
        name: Default
        demands:
        - AZP_${{ provider }}
      variables:
      - group: artifacts
      workspace:
        clean: all
      timeoutInMinutes: 90

      steps:
      - checkout: self
        submodules: recursive

      - ${{ if image.parent }}:
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: specific
            project: packer
            pipeline: ${{ join('-', image.parent) }}-${{ provider }}-core
            downloadType: single
            artifactName: ${{ join('-', image.parent) }}-${{ provider }}-core-build

        - task: ExtractFiles@1
          inputs:
            archiveFilePatterns: $(Build.ArtifactStagingDirectory)/**/build.*
            destinationFolder: build/${{ join('-', image.parent) }}

        - task: DeleteFiles@1
          inputs:
            sourceFolder: $(Build.ArtifactStagingDirectory)
            contents: '**'

      - powershell: |
          dotnet cake ci.cake --target=test --configuration=${{ join('-', image.name) }}-${{ provider }}-core
        displayName: Build

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: build/${{ join('-', image.name) }}/${{ provider }}-core
          archiveType: tar
          tarCompression: none
          archiveFile: $(Build.ArtifactStagingDirectory)/build.tar

      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: ${{ join('-', image.name) }}-${{ provider }}-core-build
          pathtoPublish: $(Build.ArtifactStagingDirectory)/build.tar
          publishLocation: filePath
          targetPath: $(artifacts-targetpath)

      - task: DeleteFiles@1
        inputs:
          sourceFolder: $(Build.ArtifactStagingDirectory)
          contents: '**'
        condition: always()

      - powershell: |
          dotnet cake ci.cake --target=clean
        displayName: Clean
        condition: always()
