parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: ${{ join('_', image.name) }}_${{ provider }}_init_build
      displayName: Build ${{ join('-', image.name) }}-${{ provider }}-init
      pool:
        name: Default
        demands:
        - AZP_${{ provider }}
      variables:
      - group: artifacts
      workspace:
        clean: all
      timeoutInMinutes: 90

      steps:
      - checkout: self
        submodules: recursive

      - powershell: |
          dotnet cake build.cake --target=test --configuration=${{ join('-', image.name) }}-${{ provider }}-init
        displayName: Build

      - powershell: |
          dotnet cake build.cake --target=clean
        displayName: Clean Build
        condition: always()
