parameters:
  images: []
  providers: [ 'hyperv' ]
  configurations: [ 'vagrant' ]

stages:
- stage: build
  displayName: Build

  jobs:
  - template: ./jobs.build.yml
    parameters:
      images: ${{ parameters.images }}
      providers: ${{ parameters.providers }}
      configurations: ${{ parameters.configurations }}

- stage: deploy
  displayName: Deploy

  variables:
  - group: environment-vagrantcloud

  jobs:
  - template: ./jobs.deploy.yml
    parameters:
      images: ${{ parameters.images }}
      providers: ${{ parameters.providers }}
      configurations: ${{ parameters.configurations }}
