parameters:
  images: []
  providers: [ 'virtualbox', 'hyperv' ]
  configurations: [ 'core' ]

stages:
- stage: build
  displayName: Build

  jobs:
  - template: ./jobs.build.yml
    parameters:
      images: ${{ parameters.images }}
      providers: ${{ parameters.providers }}
      configurations: ${{ parameters.configurations }}
