parameters:
  images: []
  providers: [ 'virtualbox', 'hyperv' ]
  configurations: [ 'vagrant' ]

stages:
- stage: default
  displayName: Default

  jobs:
  - template: ./jobs.build.yml
    parameters:
      images: ${{ parameters.images }}
      providers: ${{ parameters.providers }}
      configurations: ${{ parameters.configurations }}

  - template: ./jobs.deploy.yml
    parameters:
      images: ${{ parameters.images }}
      providers: ${{ parameters.providers }}
      configurations: ${{ parameters.configurations }}
