parameters:
  images: []
  providers: [ 'virtualbox', 'hyperv' ]

stages:
- stage: core
  displayName: Core

  jobs:
  - template: ./jobs.build.yml
    parameters:
      images: ${{ parameters.images }}
      providers: ${{ parameters.providers }}
      configurations:
      - core

- stage: vagrant
  displayName: Vagrant

  jobs:
  - template: ./jobs.build.yml
    parameters:
      images: ${{ parameters.images }}
      providers: ${{ parameters.providers }}
      configurations: [ 'vagrant' ]

  - template: ./jobs.deploy.yml
    parameters:
      images: ${{ parameters.images }}
      providers: ${{ parameters.providers }}
      configurations:
      - vagrant
