parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: ${{ join('_', image.name) }}_${{ provider }}_vagrant_build
      displayName: Build ${{ join('-', image.name) }}-${{ provider }}-vagrant
      pool:
        name: Default
        demands:
        - AZP_${{ provider }}
      workspace:
        clean: all

      steps:
      - checkout: self
        submodules: recursive

      - powershell: |
          dotnet cake build.cake --target=test --configuration=${{ join('-', image.name) }}-${{ provider }}-vagrant
        displayName: Build
