parameters:
  images: []
  providers: []

jobs:
- ${{ each image in parameters.images }}:
  - ${{ each provider in parameters.providers }}:
    - job: ${{ join('_', image.name) }}_${{ provider }}_vagrant_deploy
      displayName: Deploy ${{ join('-', image.name) }}-${{ provider }}-vagrant
      pool:
        name: Default
        demands:
        - AZP_${{ provider }}
      variables:
      - group: environment-vagrantcloud
      workspace:
        clean: all

      steps:
      - checkout: self
        submodules: recursive

      - powershell: |
          dotnet cake build.cake --target=publish --configuration=${{ join('-', image.name) }}-${{ provider }}-vagrant
        displayName: Build
        env:
          VAGRANT_CLOUD_TOKEN: $(environment-vagrant-cloud-token)
