trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2022s-nocm-hyperv-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2022s-nocm
      provider: hyperv
      configuration: vagrant
      parent: ws2022s-nocm

  - template: ../../cd-stages.yml
    parameters:
      image: ws2022s-nocm
      provider: hyperv
      configuration: vagrant
