trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: ubuntu-server.2004-lts.virtualbox

stages:
  - template: ../../stages.yml
    parameters:
      sample: ubuntu-desktop
      image: 2004-lts-ubuntu
      provider: virtualbox
