trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w101909e-virtualbox-core
      trigger:
        branches:
          include:
            - '*'

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w101909e
      provider: virtualbox
      configuration: vagrant
      parent: w101909e

  - template: ../../cd-stages.yml
    parameters:
      image: w101909e
      provider: virtualbox
      configuration: vagrant
