trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: u1804d-hyperv-core
      trigger:
        branches:
          include:
            - master

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: u1804d
      provider: hyperv
      configuration: vagrant
      parent: u1804d

  - template: ../../cd-stages.yml
    parameters:
      image: u1804d
      provider: hyperv
      configuration: vagrant
