trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-server.2022-standard.virtualbox

stages:
  - template: ../../stages.yml
    parameters:
      sample: sql-server
      image: 2019-developer-windows-server
      provider: virtualbox
