trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2019sc-dc-virtualbox-core
      trigger:
        branches:
          include:
            - master

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2019sc-dc
      provider: virtualbox
      configuration: vagrant
      parent: ws2019sc-dc

  - template: ../../cd-stages.yml
    parameters:
      image: ws2019sc-dc
      provider: virtualbox
      configuration: vagrant
