trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w1122h2e-hyperv-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w1122h2e-vs19c
      provider: hyperv
      configuration: core
      parent: w1122h2e
