trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: w102004e-virtualbox-core
      trigger:
        branches:
          include:
            - '*'

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: w102004e
      provider: virtualbox
      configuration: vagrant
      parent: w102004e

  - template: ../../cd-stages.yml
    parameters:
      image: w102004e
      provider: virtualbox
      configuration: vagrant
