trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: wsipsc-hyperv-core
      trigger: true

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: wsipsc
      provider: hyperv
      configuration: vagrant
      parent: wsipsc

  - template: ../../cd-stages.yml
    parameters:
      image: wsipsc
      provider: hyperv
      configuration: vagrant
