trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: wsipsc-virtualbox-core
      trigger:
        branches:
          include:
            - master

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: wsipsc
      provider: virtualbox
      configuration: vagrant
      parent: wsipsc

  - template: ../../cd-stages.yml
    parameters:
      image: wsipsc
      provider: virtualbox
      configuration: vagrant
