trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2019s-iis-hyperv-core
      trigger:
        branches:
          include:
            - master

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2019s-iis
      provider: hyperv
      configuration: vagrant
      parent: ws2019s-iis

  - template: ../../cd-stages.yml
    parameters:
      image: ws2019s-iis
      provider: hyperv
      configuration: vagrant
