trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: u1804s-virtualbox-core

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: u1804d
      provider: virtualbox
      configuration: core
      parent: u1804s
