trigger: none
pr: none

resources:
  pipelines:
    - pipeline: parent
      source: ws2022sc-vmware-core
      trigger:
        branches:
          include:
            - master

stages:
  - template: ../../ci-stages.yml
    parameters:
      image: ws2022sc
      provider: vmware
      configuration: vagrant
      parent: ws2022sc

  - template: ../../cd-stages.yml
    parameters:
      image: ws2022sc
      provider: vmware
      configuration: vagrant
